'use strict';

// The CLI, end to end: a real server, the real `bin/wrpc.js` in a child
// process, and then the compiler on what came out. The last step is the point —
// a codegen tool that emits types nothing type-checks against is a text
// generator, so the generated contract is fed straight into `connect<Api>()`
// and TypeScript is asked whether it holds up.

const { test } = require('node:test');
const assert = require('node:assert');
const path = require('node:path');
const os = require('node:os');
const { existsSync } = require('node:fs');
const { mkdtemp, readFile, rm, writeFile } = require('node:fs/promises');
const { execFile } = require('node:child_process');

const { Server, defineRouter, procedure } = require('../../index.js');

const ROOT = path.join(__dirname, '..', '..');
const BIN = path.join(ROOT, 'bin', 'wrpc.js');
const TSC = path.join(ROOT, 'node_modules', '.bin', 'tsc');

const run = (file, args, options = {}) =>
  new Promise((resolve) => {
    execFile(file, args, { cwd: ROOT, ...options }, (error, stdout, stderr) => {
      resolve({ code: error?.code ?? 0, stdout, stderr, error });
    });
  });

// The router carries `signature` descriptors: they are what turns introspection
// from a list of names into something worth generating types from.
const router = defineRouter({
  chat: {
    send: procedure({
      access: 'public',
      meta: { description: 'Post a message to a room' },
      signature: { args: { room: 'string', text: 'string', 'replyTo?': 'string' }, returns: { id: 'string' } },
      handler: async (_context, { text }) => ({ id: `id-${text}` }),
    }),
    list: procedure({
      access: 'public',
      signature: { args: { room: 'string' }, returns: [{ id: 'string', text: 'string' }] },
      handler: async () => [{ id: '1', text: 'hi' }],
    }),
    // No signature at all: still callable, just not described.
    ping: procedure({ access: 'public', handler: async () => true }),
    onMessage: procedure.subscription({
      access: 'public',
      signature: { args: { room: 'string' }, data: { text: 'string', tags: 'string[]' } },
      handler: async function* () {
        yield { text: 'hi', tags: ['a'] };
      },
    }),
    // An undescribed subscription: the generated marker has to stay callable
    // both ways (`subscribe()` and `subscribe(args)`), which is why the args
    // slot is `any` rather than `unknown` — `unknown` would refuse the former.
    onRaw: procedure.subscription({
      access: 'public',
      handler: async function* () {
        yield 1;
      },
    }),
  },
  'auth.1': {
    signIn: procedure({
      access: 'public',
      signature: { args: { login: 'string' }, returns: { token: 'string' } },
      handler: async () => ({ token: 't' }),
    }),
  },
});

test('CLI e2e: generates a contract from a live server and type-checks it', async (t) => {
  const server = new Server({
    router,
    host: '127.0.0.1',
    port: 0,
    protocol: 'http',
    logger: false,
    timeouts: { bind: 100 },
  });
  await server.listen();
  t.after(() => server.close());
  const { port } = server.address();

  const dir = await mkdtemp(path.join(os.tmpdir(), 'wrpc-types-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const out = path.join(dir, 'api.d.ts');

  const generated = await run(process.execPath, [BIN, 'types', `http://127.0.0.1:${port}/api`, '--out', out]);
  assert.strictEqual(generated.code, 0, `wrpc types failed: ${generated.stderr}`);
  assert.strictEqual(generated.stderr, '', 'a well-described router generates without warnings');

  const contract = await readFile(out, 'utf8');
  assert.strictEqual(
    contract,
    [
      '// Generated by `wrpc types`. Do not edit — re-run the command instead.',
      `// Source: http://127.0.0.1:${port}/api`,
      '',
      "import type { SubscriptionContract } from '@alexify/wrpc';",
      '',
      'export interface Api {',
      "  'auth.1': {",
      '    signIn(args: { login: string }): Promise<{ token: string }>;',
      '  };',
      '  chat: {',
      '    list(args: { room: string }): Promise<Array<{ id: string; text: string }>>;',
      '    onMessage: SubscriptionContract<{ room: string }, { text: string; tags: string[] }>;',
      '    onRaw: SubscriptionContract<any, unknown>;',
      '    ping(args?: unknown): Promise<unknown>;',
      '    /** Post a message to a room */',
      '    send(args: { room: string; text: string; replyTo?: string }): Promise<{ id: string }>;',
      '  };',
      '  system: {',
      '    introspect(args?: unknown): Promise<unknown>;',
      '  };',
      '}',
      '',
    ].join('\n'),
  );

  // Re-running must produce the same bytes: a diff in a generated file should
  // mean the server changed, never that the generator is unstable.
  const again = await run(process.execPath, [BIN, 'types', `http://127.0.0.1:${port}/api`, '--out', out]);
  assert.strictEqual(again.code, 0);
  assert.strictEqual(await readFile(out, 'utf8'), contract);

  // --units narrows it, and the filter is honoured server-side
  const narrow = path.join(dir, 'narrow.d.ts');
  const filtered = await run(process.execPath, [
    BIN,
    'types',
    `http://127.0.0.1:${port}/api`,
    '--units',
    'chat',
    '--out',
    narrow,
    '--interface',
    'ChatApi',
  ]);
  assert.strictEqual(filtered.code, 0, filtered.stderr);
  const narrowed = await readFile(narrow, 'utf8');
  assert.match(narrowed, /export interface ChatApi \{/);
  assert.ok(!narrowed.includes("'auth.1'"), '--units chat must not describe auth.1');
  assert.ok(!narrowed.includes('system:'), '--units chat must not describe system');

  await t.test('the generated contract satisfies the typed client', async (sub) => {
    if (!existsSync(TSC)) return void sub.skip('typescript is not installed');
    // The generated file imports '@alexify/wrpc' exactly as a consumer's would;
    // `paths` supplies the resolution a consumer gets from node_modules.
    await writeFile(
      path.join(dir, 'use.ts'),
      [
        "import { connect } from '@alexify/wrpc';",
        "import type { Api } from './api.js';",
        '',
        'export const run = async () => {',
        "  const client = await connect<Api>('ws://127.0.0.1:1/');",
        "  await client.load('chat', 'auth.1');",
        "  const sent: { id: string } = await client.api.chat.send({ room: 'a', text: 'hi' });",
        "  const rows: Array<{ id: string; text: string }> = await client.api.chat.list({ room: 'a' });",
        '  const anything: unknown = await client.api.chat.ping();',
        "  const token: string = (await client.api['auth.1'].signIn({ login: 'me' })).token;",
        '  const texts: Array<string> = [];',
        "  const feed = client.api.chat.onMessage.subscribe({ room: 'a' }, {",
        '    onData: (data) => void texts.push(data.text),',
        '  });',
        '  feed.unsubscribe();',
        '  // An undescribed subscription stays callable with args and without',
        '  client.api.chat.onRaw.subscribe().unsubscribe();',
        '  client.api.chat.onRaw.subscribe({ whatever: true }).unsubscribe();',
        '  return { sent, rows, anything, token, texts };',
        '};',
        '',
        '// ...and the contract is precise enough to REJECT the wrong thing.',
        'export const wrong = async () => {',
        "  const client = await connect<Api>('ws://127.0.0.1:1/');",
        '  // @ts-expect-error a room is a string',
        '  await client.api.chat.send({ room: 1, text: 2 });',
        '  // @ts-expect-error a subscription is not callable',
        "  await client.api.chat.onMessage({ room: 'a' });",
        '  // @ts-expect-error there is no such unit',
        "  await client.load('nope');",
        '};',
        '',
      ].join('\n'),
    );
    await writeFile(
      path.join(dir, 'tsconfig.json'),
      JSON.stringify({
        compilerOptions: {
          strict: true,
          noEmit: true,
          target: 'ES2022',
          module: 'NodeNext',
          moduleResolution: 'NodeNext',
          skipLibCheck: true,
          // No baseUrl: TypeScript 7 removed it, and an absolute `paths` entry
          // needs no base to resolve against.
          paths: { '@alexify/wrpc': [path.join(ROOT, 'index.d.ts')] },
        },
        files: ['api.d.ts', 'use.ts'],
      }),
    );
    const checked = await run(TSC, ['-p', path.join(dir, 'tsconfig.json')], { cwd: dir });
    assert.strictEqual(checked.code, 0, `tsc rejected the generated contract:\n${checked.stdout}${checked.stderr}`);
  });
});

test('CLI e2e: a server that is not there fails with a message, not a stack', async () => {
  // Port 1 is privileged and unbound: a connection there is refused at once.
  const result = await run(process.execPath, [BIN, 'types', 'http://127.0.0.1:1/api', '--out', '-']);
  assert.strictEqual(result.code, 1);
  assert.match(result.stderr, /^wrpc types: Cannot reach http:\/\/127\.0\.0\.1:1\/api: /);
  assert.ok(!result.stderr.includes('    at '), 'an expected failure must not print a stack');
  assert.strictEqual(result.stdout, '');
});

test('CLI e2e: --out - writes the contract to stdout', async (t) => {
  const server = new Server({
    router,
    host: '127.0.0.1',
    port: 0,
    protocol: 'http',
    logger: false,
    timeouts: { bind: 100 },
  });
  await server.listen();
  t.after(() => server.close());
  const { port } = server.address();

  const result = await run(process.execPath, [
    BIN,
    'types',
    `http://127.0.0.1:${port}/api`,
    '--units',
    'chat',
    '--out',
    '-',
  ]);
  assert.strictEqual(result.code, 0, result.stderr);
  assert.match(result.stdout, /export interface Api \{/);
  assert.match(result.stdout, /onMessage: SubscriptionContract</);
});
